version: "2.1"

services:

  gradle-redis-store-app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ["gradle-redis-store-app-data:/home/appuser"]
    networks: [backing-services]
    ports: ["8080:8080"]
    restart: unless-stopped
    mem_limit: 838860800 # 800Mb

volumes:
  gradle-redis-store-app-data: {}

networks:
  backing-services:
    driver: bridge
