version: "2.1"

services:

  mysql:
    image: mysql:8.0.3
    #image: mysql:5.7.19
    ##image: healthcheck/mysql
    ports: ["3306:3306"]
    networks: [backing-services]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

networks:
  backing-services:
    driver: bridge
