version: "2.1"

services:

  rabbitmq:
    #image: healthcheck/rabbitmq:alpine
    image: rabbitmq:3.6.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [backing-services]

volumes:
  rabbitmq-data: {}

networks:
  backing-services:
    driver: bridge
