version: "2.1"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - 'http.cors.allow-origin: "/.*/"'
      - "http.cors.enabled: true"
      - "node.master: true"
      - 'http.cors.allow-headers : "X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization"'
      - 'http.cors.allow-methods: "OPTIONS, HEAD, GET, POST, PUT, DELETE"'
      - "http.cors.allow-credentials: true"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes: ["elasticsearch-data:/usr/share/elasticsearch/data"]
    ports: ["9200:9200"]
    networks: [backing-services]
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:changeme -I -s -L http://127.0.0.1:9200/ || exit 1"]
      #interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports: ["5601:5601"]
    mem_limit: 512m
    networks:
      - backing-services
      - public
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5601/ || exit 1"]
      #interval: 10s
      timeout: 5s
      retries: 5

volumes:
  elasticsearch-data:
  data-data:
  blog-data:

networks:
  backing-services:
  public:
