version: "2.1"
services:
  soap-ws-app:
    image: openjdk:8u131-jre-alpine
    links: ["soap-ws-db:db"]
    depends_on: [soap-ws-db]
    ports:
      - "8080:8080"
    networks: [soap-ws-network]
    volumes:
      - "soap-ws-app-data:/var/app"
      - "../../../../services/ws-service/build/libs/ws-service-0.0.3.jar:/var/app/app.jar"
    environment:
      DB_HOST: db
      JAVA_OPTS: ""
    #command: sh -c "mkdir -f /var/app # not needed with docker-compose"
    entrypoint: sh -c "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /var/app/app.jar"
  soap-ws-db:
    image: healthcheck/postgres:alpine
    container_name: soap-ws-db
    ports: ["5432:5432"]
    networks: [soap-ws-network]
    volumes: ["soap-ws-db-data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  soap-ws-app-data: {}
  soap-ws-db-data: {}
networks:
  soap-ws-network:
    driver: bridge
