version: "2.1"

services:

  postgres:
    image: postgres:10.0-alpine
    #image: postgres:9.6.5-alpine
    ##image: healthcheck/postgres
    ports: ["5432:5432"]
    networks: [backing-services]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

networks:
  backing-services:
    driver: bridge
