version: "2.1"
services:
  db:
    image: healthcheck/postgres:alpine
    volumes: ["db-data:/var/lib/postgresql/data"]
    networks: [backing-services]
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  db-data: {}
networks:
  backing-services:
    driver: bridge
